# version: 2
# jobs:
#    build:
#      docker:
#        - image: circleci/mongo:3.4.4

#   deployment:
#     production:
#       branch: master
#       commands:
#       # The following few lines set up the heroku-toolbet CLI so we
#       # can deploy the app. Read more in the CircleCI docs:
#       # https://circleci.com/docs/1.0/continuous-deployment-with-heroku/
#       - npm start



version: 2
machine:
  node:
    version:
      latest

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/mongo:3.4.4
      - image: circleci/mysql:5.7.18
      - image: circleci/node:7.7.2

    working_directory: ~/repo

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: newman run postman.json -e env.json