version: 2
jobs:
  build:
    docker: 
      - image: node:7.10.0
      - image: mongo:3.5.6
      - image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=java@123
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_DATABASE=hr_recruit_dev
          - MYSQL_HOST=127.0.0.1

    working_directory: /home/ubuntu/hr-recruit

    steps:
      - checkout
      - run: mkdir -p /home/ubuntu/hr-recruit
      - run: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
      - run: echo "deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.0.list
      - run: apt-get update
      - run: apt-get install -y mongodb-org
      - run: service mongod restart
      - run: npm install
      - run: npm install pm2 -g
      - run: pm2 start npm --name hr-recruit -- start
      - run: npm install -g newman
      - run: pm2 logs
      - run: newman run postman.json -e env.json